[project]
name = "closta"
version = "0.3"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "dearpygui",
    "pywinctl",
    "pystray",
    "pymonctl",
    "pillow",
    "pyautogui",
    "pywin32",
]

[dependency-groups]
test = [
    "pytest>=8.3.5",
]

[project.optional-dependencies]
dev = [
    "nuitka",
]